from .exception import MatrixError
from .base import MatrixBase
class Matrix(MatrixBase):
    def clone(self):
        return Matrix(self.args)

    def __add__(self, other: MatrixBase):...

    def __radd__(self, other: MatrixBase):...

    def __sub__(self, other: MatrixBase):...

    def __rsub__(self, other: MatrixBase):...

    def __mul__(self, other: MatrixBase):...

    def __rmul__(self, other: MatrixBase):...

    def __truediv__(self, other: MatrixBase):...

    def __rtruediv__(self, other: MatrixBase):...